# Generated by Django 5.0.4 on 2024-05-02 06:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.TextField(max_length=255)),
                ('endereco', models.TextField(max_length=255)),
                ('contato', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.TextField(max_length=255)),
                ('idade_pet', models.IntegerField()),
                ('data_aniversario', models.DateField()),
                ('raca', models.TextField(max_length=255)),
                ('porte', models.TextField(max_length=255)),
                ('pelagem', models.TextField(max_length=255)),
                ('foto', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banho_tipo', models.TextField(max_length=255)),
                ('valor_banho', models.FloatField()),
                ('tosa_tipo', models.TextField(max_length=255)),
                ('valor_tosa', models.FloatField()),
                ('observacao', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=255)),
                ('hora_inicial', models.TimeField(auto_now_add=True)),
                ('hora_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atual', models.DateField(default=datetime.date.today)),
                ('data_agendada', models.DateField()),
            ],
        ),
    ]
