# Generated by Django 5.0.4 on 2024-05-07 19:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banho_tipo', models.CharField(max_length=255)),
                ('valor_banho', models.FloatField()),
                ('tosa_tipo', models.CharField(max_length=255)),
                ('valor_tosa', models.FloatField()),
                ('item', models.CharField(max_length=100)),
                ('valor_item', models.FloatField()),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 5, 7, 19, 11, 28, 508312, tzinfo=datetime.timezone.utc))),
                ('data_agendada', models.DateField()),
                ('observacao', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro_servico',
        ),
        migrations.DeleteModel(
            name='Cadastro_tempo',
        ),
        migrations.RemoveField(
            model_name='cadastro_pet',
            name='video',
        ),
        migrations.AddField(
            model_name='cadastro_pet',
            name='nome_dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_pet.cadastro_cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro_cliente',
            name='contato',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastro_cliente',
            name='endereco',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cadastro_cliente',
            name='nome_cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro_pet',
            name='nome_pet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro_pet',
            name='pelagem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro_pet',
            name='porte',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro_pet',
            name='raca',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='cadastro_venda',
            name='cliente_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_pet.cadastro_cliente'),
        ),
        migrations.AddField(
            model_name='cadastro_venda',
            name='pet_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_pet.cadastro_pet'),
        ),
    ]
