# Generated by Django 5.0.4 on 2024-05-15 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet', '0002_cadastro_venda_delete_cadastro_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_venda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 1, 56, 34, 339038, tzinfo=datetime.timezone.utc)),
        ),
    ]
